import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { adminApiService, KeyAccount, Region } from '../services/api'
import { 
  Plus, 
  Search, 
  Edit, 
  Trash2,
  XCircle,
  Building2,
  UserCheck,
  UserX,
  Power,
  Settings,
  FileText
} from 'lucide-react'

interface KeyAccountModalProps {
  isOpen: boolean
  onClose: () => void
  keyAccount?: KeyAccount | null
  onSave: (keyAccountData: Partial<KeyAccount>) => Promise<void>
  isEditing: boolean
}

const KeyAccountModal: React.FC<KeyAccountModalProps> = ({ 
  isOpen, 
  onClose, 
  keyAccount, 
  onSave, 
  isEditing 
}) => {
  const [formData, setFormData] = useState<Partial<KeyAccount>>({
    name: '',
    email: '',
    contact: '',
    description: '',
    account_number: '',
    is_active: 1,
    region: ''
  })
  const [saving, setSaving] = useState(false)
  const [regions, setRegions] = useState<Region[]>([])
  const [loadingRegions, setLoadingRegions] = useState(false)

  useEffect(() => {
    if (isOpen) {
      fetchRegions()
      if (isEditing && keyAccount) {
        setFormData({
          name: keyAccount.name || '',
          email: keyAccount.email || '',
          contact: keyAccount.contact || '',
          description: keyAccount.description || '',
          account_number: keyAccount.account_number || '',
          is_active: keyAccount.is_active !== undefined ? keyAccount.is_active : 1,
          region: keyAccount.region || '',
          type: keyAccount.type || 'key_account'
        })
      } else {
        setFormData({
          name: '',
          email: '',
          contact: '',
          description: '',
          account_number: '', // Will be auto-generated by backend
          is_active: 1,
          type: 'key_account', // Set default type for key accounts
          region: ''
        })
      }
    }
  }, [isOpen, isEditing, keyAccount])

  const fetchRegions = async () => {
    try {
      setLoadingRegions(true)
      const data = await adminApiService.getRegions()
      // Filter only active regions
      const activeRegions = data.filter(region => region.status === 1)
      setRegions(activeRegions)
    } catch (error) {
      console.error('Error fetching regions:', error)
      setRegions([])
    } finally {
      setLoadingRegions(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      setSaving(true)
      await onSave(formData)
      onClose()
    } catch (error) {
      console.error('Error saving key account:', error)
      alert(`Failed to save key account: ${(error as any).message || 'Unknown error'}`)
    } finally {
      setSaving(false)
    }
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: value
    }))
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded p-2 w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        <div className="flex justify-between items-center mb-1.5">
          <h2 className="text-sm font-semibold">
            {isEditing ? 'Edit Key Account' : 'Add New Key Account'}
          </h2>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700"
          >
            <XCircle className="h-3.5 w-3.5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-1.5">
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-0.5 text-[11px]">
              Name *
            </label>
            <input
              type="text"
              name="name"
              value={formData.name || ''}
              onChange={handleChange}
              required
              className="w-full px-1.5 py-0.5 text-[11px] border border-gray-300 rounded focus:ring-1 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter account name"
            />
          </div>

          <div>
            <label className="block text-xs font-medium text-gray-700 mb-0.5 text-[11px]">
              Email *
            </label>
            <input
              type="email"
              name="email"
              value={formData.email || ''}
              onChange={handleChange}
              required
              className="w-full px-1.5 py-0.5 text-[11px] border border-gray-300 rounded focus:ring-1 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter email address"
            />
          </div>

          <div>
            <label className="block text-xs font-medium text-gray-700 mb-0.5 text-[11px]">
              Contact *
            </label>
            <input
              type="text"
              name="contact"
              value={formData.contact || ''}
              onChange={handleChange}
              required
              className="w-full px-1.5 py-0.5 text-[11px] border border-gray-300 rounded focus:ring-1 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter contact number"
            />
          </div>

          <div>
            <label className="block text-xs font-medium text-gray-700 mb-0.5 text-[11px]">
              Type *
            </label>
            <select
              name="type"
              value={formData.type || 'key_account'}
              onChange={handleChange}
              required
              className="w-full px-1.5 py-0.5 text-[11px] border border-gray-300 rounded focus:ring-1 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="key_account">Key Account</option>
              <option value="client">Client</option>
            </select>
          </div>

          <div>
            <label className="block text-xs font-medium text-gray-700 mb-0.5 text-[11px]">
              Region
            </label>
            <select
              name="region"
              value={formData.region || ''}
              onChange={handleChange}
              disabled={loadingRegions}
              className="w-full px-1.5 py-0.5 text-[11px] border border-gray-300 rounded focus:ring-1 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-50 disabled:cursor-not-allowed"
            >
              <option value="">Select a region</option>
              {regions.map((region) => (
                <option key={region.id} value={region.name}>
                  {region.name}
                </option>
              ))}
            </select>
            {loadingRegions && (
              <p className="text-[9px] text-gray-500 mt-0.5">Loading regions...</p>
            )}
          </div>

          {isEditing && formData.account_number && (
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-0.5 text-[11px]">
                Account Number
              </label>
              <input
                type="text"
                name="account_number"
                value={formData.account_number || ''}
                readOnly
                className="w-full px-1.5 py-0.5 text-[11px] border border-gray-300 rounded bg-gray-50 text-gray-600 cursor-not-allowed"
                placeholder="Auto-generated"
              />
              <p className="text-[9px] text-gray-500 mt-0.5">Account number is auto-generated and cannot be changed</p>
            </div>
          )}
          {!isEditing && (
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-0.5 text-[11px]">
                Account Number
              </label>
              <input
                type="text"
                value="Auto-generated"
                readOnly
                disabled
                className="w-full px-1.5 py-0.5 text-[11px] border border-gray-300 rounded bg-gray-50 text-gray-500 cursor-not-allowed"
              />
              <p className="text-[9px] text-gray-500 mt-0.5">
                Account number will be auto-generated ({formData.type === 'client' ? 'CLT' : 'KA'}-XXXXX-XXXX)
              </p>
            </div>
          )}

          <div>
            <label className="block text-xs font-medium text-gray-700 mb-0.5 text-[11px]">
              Description
            </label>
            <textarea
              name="description"
              value={formData.description || ''}
              onChange={handleChange}
              rows={3}
              className="w-full px-1.5 py-0.5 text-[11px] border border-gray-300 rounded focus:ring-1 focus:ring-blue-500 focus:border-transparent"
              placeholder="Enter description (optional)"
            />
          </div>

          <div>
            <label className="block text-xs font-medium text-gray-700 mb-0.5 text-[11px]">
              Status *
            </label>
            <select
              name="is_active"
              value={formData.is_active !== undefined ? formData.is_active : 1}
              onChange={(e) => setFormData(prev => ({ 
                ...prev, 
                is_active: Number(e.target.value) 
              }))}
              required
              className="w-full px-1.5 py-0.5 text-[11px] border border-gray-300 rounded focus:ring-1 focus:ring-blue-500 focus:border-transparent"
            >
              <option value={1}>Active</option>
              <option value={0}>Inactive</option>
            </select>
          </div>

          <div className="flex justify-end gap-1 pt-1.5">
            <button
              type="button"
              onClick={onClose}
              className="px-1.5 py-0.5 text-[11px] border border-gray-300 rounded text-gray-700 hover:bg-gray-50"
              disabled={saving}
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="px-1.5 py-0.5 text-[11px] bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {saving ? 'Saving...' : isEditing ? 'Update' : 'Create'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

const KeyAccounts: React.FC = () => {
  const navigate = useNavigate()
  const [keyAccounts, setKeyAccounts] = useState<KeyAccount[]>([])
  const [loading, setLoading] = useState(true)
  const [searchTerm, setSearchTerm] = useState('')
  const [statusFilter, setStatusFilter] = useState<'all' | 'active' | 'inactive'>('all')
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [editingKeyAccount, setEditingKeyAccount] = useState<KeyAccount | null>(null)
  const [deletingKeyAccount, setDeletingKeyAccount] = useState<number | null>(null)
  const [togglingKeyAccount, setTogglingKeyAccount] = useState<number | null>(null)

  useEffect(() => {
    fetchKeyAccounts()
  }, [])

  const fetchKeyAccounts = async () => {
    try {
      console.log('🏢 [KeyAccounts] Fetching key accounts...')
      setLoading(true)
      const data = await adminApiService.getKeyAccounts()
      console.log('✅ [KeyAccounts] Key accounts fetched:', data)
      setKeyAccounts(Array.isArray(data) ? data : [])
    } catch (error) {
      console.error('❌ [KeyAccounts] Error fetching key accounts:', error)
      setKeyAccounts([])
    } finally {
      setLoading(false)
    }
  }

  const handleCreate = () => {
    setEditingKeyAccount(null)
    setIsModalOpen(true)
  }

  const handleEdit = (keyAccount: KeyAccount) => {
    setEditingKeyAccount(keyAccount)
    setIsModalOpen(true)
  }

  const handleSave = async (keyAccountData: Partial<KeyAccount>) => {
    try {
      if (editingKeyAccount) {
        // When editing, don't send account_number if it wasn't changed
        const updateData = { ...keyAccountData }
        // Keep account_number only if it exists and is different (though it shouldn't be editable)
        if (!updateData.account_number || updateData.account_number === editingKeyAccount.account_number) {
          delete updateData.account_number
        }
        await adminApiService.updateKeyAccount(editingKeyAccount.id, updateData)
      } else {
        // When creating, don't send account_number - let backend auto-generate it
        const createData = { ...keyAccountData }
        delete createData.account_number
        // Ensure type is set (default to 'key_account' if not provided)
        if (!createData.type) {
          createData.type = 'key_account'
        }
        await adminApiService.createKeyAccount(createData as Omit<KeyAccount, 'id' | 'created_at' | 'updated_at'>)
      }
      await fetchKeyAccounts()
    } catch (error) {
      console.error('Error saving key account:', error)
      throw error
    }
  }

  const handleDelete = async (id: number) => {
    if (!confirm('Are you sure you want to delete this key account? This action cannot be undone.')) {
      return
    }

    try {
      setDeletingKeyAccount(id)
      await adminApiService.deleteKeyAccount(id)
      await fetchKeyAccounts()
    } catch (error) {
      console.error('Error deleting key account:', error)
      alert(`Failed to delete key account: ${(error as any).message || 'Unknown error'}`)
    } finally {
      setDeletingKeyAccount(null)
    }
  }

  const handleToggleStatus = async (keyAccount: KeyAccount) => {
    const newStatus = keyAccount.is_active === 1 ? 0 : 1
    const action = newStatus === 1 ? 'activate' : 'deactivate'
    
    if (!confirm(`Are you sure you want to ${action} this key account?`)) {
      return
    }

    try {
      setTogglingKeyAccount(keyAccount.id)
      await adminApiService.updateKeyAccount(keyAccount.id, {
        is_active: newStatus
      })
      await fetchKeyAccounts()
    } catch (error) {
      console.error('Error toggling key account status:', error)
      alert(`Failed to ${action} key account: ${(error as any).message || 'Unknown error'}`)
    } finally {
      setTogglingKeyAccount(null)
    }
  }

  const getStatusBadge = (isActive: number) => {
    return isActive === 1 ? (
      <span className="inline-flex items-center px-1 py-0.5 rounded-full text-[9px] font-medium bg-green-100 text-green-800">
        <UserCheck className="h-2.5 w-2.5 mr-0.5" />
        Active
      </span>
    ) : (
      <span className="inline-flex items-center px-1 py-0.5 rounded-full text-[9px] font-medium bg-red-100 text-red-800">
        <UserX className="h-2.5 w-2.5 mr-0.5" />
        Inactive
      </span>
    )
  }

  const filteredKeyAccounts = keyAccounts.filter(account => {
    const matchesSearch = 
      account.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      account.email?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      account.contact?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      account.account_number?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      account.description?.toLowerCase().includes(searchTerm.toLowerCase())
    
    const matchesStatus = 
      statusFilter === 'all' ||
      (statusFilter === 'active' && account.is_active === 1) ||
      (statusFilter === 'inactive' && account.is_active === 0)
    
    return matchesSearch && matchesStatus
  })

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 p-2">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center justify-center h-64">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 p-2">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-2 flex justify-between items-center">
          <h1 className="text-xs font-bold text-gray-900">Key Accounts</h1>
          <div className="flex gap-1.5">
            <button
              onClick={() => navigate('/key-accounts/ledger')}
              className="flex items-center gap-1 px-1.5 py-0.5 text-[10px] bg-green-600 text-white rounded hover:bg-green-700"
              title="View Ledger Report"
            >
              <FileText className="h-2.5 w-2.5" />
              Ledger
            </button>
            <button
              onClick={handleCreate}
              className="flex items-center gap-1 px-1.5 py-0.5 text-[10px] bg-blue-600 text-white rounded hover:bg-blue-700"
            >
              <Plus className="h-2.5 w-2.5" />
              Add
            </button>
          </div>
        </div>

        {/* Search and Filters */}
        <div className="mb-2 space-y-1.5">
          <div className="relative">
            <Search className="absolute left-1.5 top-1/2 transform -translate-y-1/2 text-gray-400 h-3 w-3" />
            <input
              type="text"
              placeholder="Search key accounts..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-6 pr-1.5 py-0.5 text-[10px] border border-gray-300 rounded focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>
          <div>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value as 'all' | 'active' | 'inactive')}
              className="w-full px-1.5 py-0.5 text-[10px] border border-gray-300 rounded focus:ring-1 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="all">All Status</option>
              <option value="active">Active Only</option>
              <option value="inactive">Inactive Only</option>
            </select>
          </div>
        </div>

        {/* Key Accounts Table */}
        {filteredKeyAccounts.length === 0 ? (
          <div className="bg-white rounded border p-3 text-center text-[10px] text-gray-500">
            No key accounts found
          </div>
        ) : (
          <div className="bg-white rounded border overflow-hidden">
            <table className="w-full">
              <thead className="bg-gray-50 border-b">
                <tr>
                  <th className="px-2 py-1 text-left text-[10px] font-medium text-gray-700">Name</th>
                  <th className="px-2 py-1 text-left text-[10px] font-medium text-gray-700">Email</th>
                  <th className="px-2 py-1 text-left text-[10px] font-medium text-gray-700">Contact</th>
                  <th className="px-2 py-1 text-left text-[10px] font-medium text-gray-700">Account Number</th>
                  <th className="px-2 py-1 text-left text-[10px] font-medium text-gray-700">Description</th>
                  <th className="px-2 py-1 text-left text-[10px] font-medium text-gray-700">Status</th>
                  <th className="px-2 py-1 text-right text-[10px] font-medium text-gray-700">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {filteredKeyAccounts.map((account) => (
                  <tr key={account.id} className="hover:bg-gray-50">
                    <td className="px-2 py-1 text-[10px] font-medium">{account.name}</td>
                    <td className="px-2 py-1 text-[10px] text-gray-600">{account.email || '-'}</td>
                    <td className="px-2 py-1 text-[10px] text-gray-600">{account.contact || '-'}</td>
                    <td className="px-2 py-1 text-[10px] text-gray-600">{account.account_number || '-'}</td>
                    <td className="px-2 py-1 text-[10px] text-gray-600 max-w-xs truncate" title={account.description || ''}>
                      {account.description || '-'}
                    </td>
                    <td className="px-2 py-1 text-[10px]">
                      {getStatusBadge(account.is_active)}
                    </td>
                    <td className="px-2 py-1 text-right">
                      <div className="flex justify-end gap-1.5">
                        <button
                          onClick={() => navigate(`/key-accounts/ledger?keyAccountId=${account.id}`)}
                          className="p-0.5 text-green-600 hover:text-green-800"
                          title="View Ledger"
                        >
                          <FileText className="h-3 w-3" />
                        </button>
                        <button
                          onClick={() => navigate(`/key-accounts/${account.id}/manage`)}
                          className="p-0.5 text-purple-600 hover:text-purple-800"
                          title="Manage"
                        >
                          <Settings className="h-3 w-3" />
                        </button>
                        <button
                          onClick={() => handleToggleStatus(account)}
                          disabled={togglingKeyAccount === account.id}
                          className={`p-0.5 ${
                            account.is_active === 1 
                              ? 'text-orange-600 hover:text-orange-800' 
                              : 'text-green-600 hover:text-green-800'
                          } disabled:opacity-50`}
                          title={account.is_active === 1 ? 'Deactivate' : 'Activate'}
                        >
                          {togglingKeyAccount === account.id ? (
                            <div className="animate-spin rounded-full h-3 w-3 border-2 border-current border-t-transparent"></div>
                          ) : (
                            <Power className="h-3 w-3" />
                          )}
                        </button>
                        <button
                          onClick={() => handleEdit(account)}
                          className="p-0.5 text-blue-600 hover:text-blue-800"
                          title="Edit"
                        >
                          <Edit className="h-3 w-3" />
                        </button>
                        <button
                          onClick={() => handleDelete(account.id)}
                          disabled={deletingKeyAccount === account.id}
                          className="p-0.5 text-red-600 hover:text-red-800 disabled:opacity-50"
                          title="Delete"
                        >
                          {deletingKeyAccount === account.id ? (
                            <div className="animate-spin rounded-full h-3 w-3 border-2 border-red-600 border-t-transparent"></div>
                          ) : (
                            <Trash2 className="h-3 w-3" />
                          )}
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* Key Account Modal */}
        <KeyAccountModal
          isOpen={isModalOpen}
          onClose={() => {
            setIsModalOpen(false)
            setEditingKeyAccount(null)
          }}
          keyAccount={editingKeyAccount}
          onSave={handleSave}
          isEditing={!!editingKeyAccount}
        />
      </div>
    </div>
  )
}

export default KeyAccounts

